### ISSUE TITLE
Error 403 while deleting user with unpublished changes

### ISSUE THREAD

**Issue by Nikdro** [neos/neos-development-collection#2123] opened 2018-07-30 11:28 UTC
### Description
Every time you try to delete a user that has unpublished changes in his personal workspace, you will get a 403 error.

### Steps to Reproduce

1. Create a user
2. Login as the created user
3. Change some content (but don't publish it)
4. Login as admin
5. Try to delete the user with unpublished changes.

#### Expected behavior

All changes should be discarded and the user deleted.

#### Actual behavior

403-Error: 
```
Exception #1222268609 in line 62 of /path/to/neos/releases/20180712140928/Data/Temporary/Production/SubContextLive/Cache/Code/Flow_Object_Classes/Neos_Flow_Security_Aspect_PolicyEnforcementAspect.php: Access denied for method
Method: Neos\ContentRepository\Domain\Service\Context::validateWorkspace()
Evaluated following 1 privilege target(s):
"Neos.Neos:Backend.OtherUsersPersonalWorkspaceAccess": ABSTAIN
(0 granted, 0 denied, 1 abstained)
Authenticated roles: Neos.Flow:Everybody, Neos.Flow:AuthenticatedUser, Neos.Neos:Administrator, Neos.Neos:Editor, Neos.Neos:AbstractEditor, Neos.ContentRepository:Administrator, Neos.Neos:LivePublisher
```

### Affected Versions
Got that error on Neos >= 2.3.X

**Comment by daniellienert** [comment] 2018-09-06 08:09
Hey @Nikdro,

thanks for reporting that issue. 
It was already reported, so I close this one as duplicate of #926 

Cheers,
Daniel

**Closed by daniellienert** 2018-09-06 08:09 UTC
