### ISSUE TITLE
Running ./flow node:migrate 20150716212459 throws an Exception

### ISSUE THREAD

**Issue by 2case** [neos/neos-development-collection#2051] opened 2018-05-03 15:55 UTC
### Description

When running `./flow node:migrate 20150716212459` an exception is thrown with the Neos 4.0:
```
Comments
  Migrate from some node dimensions to default dimension values, adding missing
  dimension default values.
[Syntax Error] line 0, col -1: Error: Expected Literal, got end of string.

  Type: Doctrine\ORM\Query\QueryException
  File: Packages/Libraries/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php
  Line: 54

Nested exception:
SELECT e FROM Neos\ContentRepository\Domain\Model\NodeData e WHERE

  Type: Doctrine\ORM\Query\QueryException
  File: Packages/Libraries/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php
  Line: 43
```

### Steps to Reproduce

1. Enter `./flow node:migrate 20150716212459` in your terminal

#### Expected behavior

The migration should migrate from some node dimensions to default dimension values and adding missing dimension default values.

#### Actual behavior

The exception is thrown

### Affected Versions

Neos: 4.0
Flow: 5.0

**Comment by kdambekalns** [comment] 2018-05-03 16:04
So whatever `WHERE` clause should be there, clearly is missing…

**Comment by kdambekalns** [comment] 2018-10-30 20:30
Thanks for reporting!

Finally tried this, but cannot reproduce. Also, there is only a `findAll()` call involved with this migration, so there should never even be a `WHERE` clause involved. I'll close this, but if this still reproducible for you, feel free to reopen.

In that case, please attach the stack trace written with the exception.

**Closed by kdambekalns** 2018-10-30 20:30 UTC
