### ISSUE TITLE
BUG: Error by trying to delete assets which are still in use in the media browser

### ISSUE THREAD

**Issue by GuangHa** [neos/neos-development-collection#5085] opened 2024-05-22 07:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you try to delete an asset which is still in use, you will get an internal error (500). Tried it in multiple installations.

![image](https://github.com/neos/neos-development-collection/assets/12826344/e612beaa-fb4d-4005-b21e-6a77bdcf36ef)

An example of the exception message I get in the logs:
```
Exception in line 516 of /var/www/vhosts/staging.jumpbox.ch/httpdocs/releases/20240515104123/Data/Temporary/Production/Cache/Code/Flow_Object_Classes/Neos_Flow_Mvc_Controller_ActionController.php: Neos\Media\Browser\Controller\AssetController::deleteAction(): Argument #1 ($asset) must be of type Neos\Media\Domain\Model\Asset, null given, called in /var/www/vhosts/staging.jumpbox.ch/httpdocs/releases/20240515104123/Data/Temporary/Production/Cache/Code/Flow_Object_Classes/Neos_Flow_Mvc_Controller_ActionController.php on line 516
```

### Expected Behavior

Another message, saying the asset is still in use and therefore unable to delete or maybe disable the delete function.

### Steps To Reproduce

1. Open media browser via Property-Editor
2. Try to delete an asset in use
3. Get Error

### Environment

```markdown
- Flow: 8.3.8
- Neos: 8.3.12
- PHP: 8.1.2
```

### Anything else?

I found this issue but it is already closed: https://github.com/neos/neos-development-collection/issues/3349

**Comment by dlubitz** [comment] 2024-08-13 13:06
Thank you for reporting. But I can't reproduce this error. Works for me with latest Neos 8.3:

![image](https://github.com/user-attachments/assets/bfd3df9f-5110-4c05-a926-917ac8580a6c)

Also your screenshot looks like you are using the Flowpack/Media-UI (https://github.com/Flowpack/media-ui/) and not the currently used Neos media library. Maybe it is a bug in this package. But I tried it also on a instance using this, and it also worked.

I'll close this for now. Please feel free to reopen, if you are sure this is a bug in Neos itself.

**Closed as completed by dlubitz** 2024-08-13 13:06 UTC
Labels: Bug, 8.3

**Comment by GuangHa** [comment] 2024-08-13 13:30
@dlubitz No, this has not been fixed, I just tested it. You have to try to delete an used image via Property-Editor for this error to occur.
![image](https://github.com/user-attachments/assets/62ab1493-464b-422b-aae5-a6e48704ac8b)

**Comment by dlubitz** [comment] 2024-08-13 13:34
Thanks @GuangHa, but this is also working for me.
![image](https://github.com/user-attachments/assets/bb45b045-b9a8-4758-bfca-59bed022cfe6)

**Comment by GuangHa** [comment] 2024-08-13 13:42
@dlubitz Hmm...thas weird, here i have a screencast for you to see what i see on demo.neos.io. Maybe you can check the exceptions?

[Screencast from 13.08.2024 15:40:54.webm](https://github.com/user-attachments/assets/7312eaa2-4e1e-4762-9fc8-2c3cf8cf8480)

**Comment by dlubitz** [comment] 2024-08-13 13:46
As I said, the error might be in the `Flowpack/Media.UI` package. Can you check the image removal with the Neos internal media library?

Otherwise I'd like to ask you to create a ticket in the package: https://github.com/Flowpack/media-ui/issues

**Comment by GuangHa** [comment] 2024-08-13 14:14
@dlubitz Ah yes, this is now fixed with the Neos internal media libray and only occurs with the new media ui. I will create a ticket there. Thanks for the reply.
