### ISSUE TITLE
[BUG] restricted user shouldn't be able to publish to live workspace

### ISSUE THREAD

**Issue by bego68** [neos/neos-development-collection#1507] opened 2017-03-30 11:49 UTC
### Description

As restricted user I shouldn't be able to publish to live workspace. Even with the **publish-button** and at the **review-area** you could press publish button and will get an error. (see screenshots)

<img width="830" alt="publishtolivemenu" src="https://cloud.githubusercontent.com/assets/7047944/24502781/852b8b94-154f-11e7-8364-edeeb49b10dc.png">

<img width="1136" alt="publishtolivereviewpanel" src="https://cloud.githubusercontent.com/assets/7047944/24502783/8535591c-154f-11e7-82e7-1004402f52d0.png">

<img width="1116" alt="publishtolivereviewpanelthrownerror" src="https://cloud.githubusercontent.com/assets/7047944/24502782/852c4c14-154f-11e7-86e3-09a8351396ec.png">

### Steps to Reproduce

1. login like restricted user 
2. change content
3. try to publish to live

#### Expected behavior

the publish (to live) should be hidden or disabled

#### Actual behavior

You can press the publish button and an error will be Thrown 

### Affected Versions

Neos: master

**Comment by Nikdro** [comment] 2019-03-20 11:27
Just tried to reproduce it. This bug is gone already. I think this one can be closed.
<img width="1920" alt="Bildschirmfoto 2019-03-20 um 12 26 44" src="https://user-images.githubusercontent.com/9807101/54680991-8e8f7300-4b0b-11e9-9ae8-3a0e7556175d.png">

**Comment by mhsdesign** [comment] 2022-07-19 16:36
Closing this because its a dup of https://github.com/neos/neos-development-collection/issues/3615

**Closed by mhsdesign** 2022-07-19 16:36 UTC
Labels: Bug
