### ISSUE TITLE
Removing a user should trigger `removeNodesWithInvalidWorkspace` node:repair logic

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-development-collection#2193] opened 2018-09-28 08:37 UTC
### Description

Currently, if you delete a user in the neos backend, the system is left with (at least) a remaining root node that no longer has a valid workspace.

#### Expected behavior
The remaining nodes with invalid workspaces should be removed automatically, like

```sh
./flow node:repair --only removeNodesWithInvalidWorkspace
```
would do, which is currently needed as a manual step to fix the issue.

### Affected Versions

Neos: 3.x, 4x

**Comment by kitsunet** [comment] 2018-09-28 08:43
Possibly duplicate of https://github.com/neos/neos-development-collection/issues/1007

**Comment by Sebobo** [comment] 2023-10-25 09:28
I tried changing the annotation in the Workspace to 
```
    /**
     * Root node data of this workspace
     *
     * @var NodeData
     * @ORM\ManyToOne
     * @ORM\JoinColumn(referencedColumnName="id",onDelete="CASCADE")
     */
    protected $rootNodeData;
```

But it didn't have any effect. Shouldn't that have been enough?
Just removed 2500 such disconnected root nodes from a project.

**Closed** 2024-09-09 07:16 UTC
Labels: P: User Management
