### ISSUE TITLE
@process on Template variables not working

### ISSUE THREAD

**Issue by rzwinge** [neos/neos-development-collection#1148] opened 2016-09-29 09:09 UTC
Here's a way to reproduce:

```
xyz = TYPO3.TypoScript:Template {
  hello = 'hello'
  hello.@process.1 = ${value + ' world'}
}
```

The template would get variable `hello` set to `hello`, instead of `hello world`, thus the processing was not applied.

A way around this issue is to wrap the processing with Value object:

```
xyz = TYPO3.TypoScript:Template {
  hello = TYPO3.TypoScript:Value {
    value = 'hello'
    value.@process.1 = ${value + ' world'}
  }
}
```

This behaviour is clearly confusing, can it be considered a bug?

**Comment by ComiR** [comment] 2016-11-22 09:33
Definitively confusing. Did this work in a previous version? I only tested it with `2.3.7`.

**Comment by kitsunet** [comment] 2017-04-25 20:07
Closing as duplicate of https://github.com/neos/neos-development-collection/issues/1109
Should be the same issue really.

**Closed by kitsunet** 2017-04-25 20:07 UTC
Labels: Bug, P: Fusion, T: Fusion
