### ISSUE TITLE
BUG: Fusion @apply converts null to empty array() in certain cases (since update to Neos 8.0)

### ISSUE THREAD

**Issue by bweinzierl** [neos/neos-development-collection#3859] opened 2022-08-16 14:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After an Update to Neos 8.0 the fusion @apply directive converts `null` to `array(empty)` in the following example (complete test component see below):

```
attributesMerged = Neos.Fusion:DataStructure {
   @apply.attributes = ${props.attributes}
   @apply.overrides = Neos.Fusion:DataStructure {
      overrideAttribute = ${'sdfsdfsdf'}
   }
}
```

With the context (props.attributes)
```
array(2)
 'test2' (5) => 'sdfsdf' (6)
 'nullAttribute' (13) => NULL
```

Return value of the DataStrucure
```
array(3)
 'test2' (5) => 'sdfsdf' (6)
 'nullAttribute' (13) => array(empty)
 'overrideAttribute' (17) => 'sdfsdfsdf' (9)
```

### Expected Behavior

null should stay null

### Steps To Reproduce

Test Component:

```
prototype(Test.TestCase:NullAttributesTest) < prototype(Neos.Fusion:Component) {

	attributes = Neos.Fusion:DataStructure

	renderer = Neos.Fusion:Component {
		@apply.props = ${props}

		attributesMerged = Neos.Fusion:DataStructure {
			@apply.attributes = ${props.attributes}
			@apply.overrides = Neos.Fusion:DataStructure {
				overrideAttribute = ${'sdfsdfsdf'}
			}
		}

		renderer = afx`
			<div>
				<Neos.Fusion:Debug>{props.attributes}</Neos.Fusion:Debug>
				<Neos.Fusion:Debug>{props.attributesMerged}</Neos.Fusion:Debug>
			</div>
		`
	}

}
```

Put this anywhere in your page rendering to see the debug output:
`
<Test.TestCase:NullAttributesTest attributes.test2={'sdfsdf'} attributes.nullAttribute={null} />`

### Environment

```markdown
- Flow: 8.0
- Neos: 8.0
- PHP: 8.1
```

**Comment by mhsdesign** [comment] 2022-08-16 17:51
Last major change (7->8) im aware of: #3645

This is not a parsing issue - entirely a runtime issue...

**Comment by mhsdesign** [comment] 2022-10-27 10:31
i tested a bit. Yes i could reproduce this.

## minimal example
```
value = Neos.Fusion:DataStructure {
    @apply.attributes = ${{
        nullAttribute: null
    }}
}
```
output expected:
`["nullAttribute" => null]`
output actual:
`["nullAttribute" => []]`



## works

```
value = Neos.Fusion:Value {
    @apply.attributes = ${{
        nullAttribute: null
    }}

    value = ${this.nullAttribute}
}
```
output as expected
`null`


## conclusion

`@apply` itself works fine - only the combination with f.x `Neos.Fusion:DataStructure` doesnt work as expected.

**Comment by mhsdesign** [comment] 2022-10-27 11:19
the issue is that the above will create an dynamic path `nullAttribute` with the partial fusion object tree:
```
array(3)
   '__eelExpression' (15) => NULL
   '__objectType' (12) => NULL
   '__value' (7) => NULL
```
see https://github.com/neos/neos-development-collection/blob/24d407118a8e55f7a96f1b69b244f9eeb8c561ac/Neos.Fusion/Classes/Core/Runtime.php#L659


this partial fusion object tree is then reached via `DataStructureImplementation::evaluate` to `AbstractArrayFusionObject::evaluateNestedProperties('Neos.Fusion:DataStructure')`

where the helper

`AbstractArrayFusionObject::isUntyped`
https://github.com/neos/neos-development-collection/blob/a761d145a16d31eaf06bd52392cd93ceb6f109d1/Neos.Fusion/Classes/FusionObjects/AbstractArrayFusionObject.php#L214

returns `false` so a nested datastructure is assumed and we render it but it will of course just return an emty array.

**Comment by mhsdesign** [comment] 2022-10-27 11:36
so i had a look.

in Neos 7.3 the partial object tree looks exactly the same:

```
array(3)
   '__eelExpression' (15) => NULL
   '__objectType' (12) => NULL
   '__value' (7) => NULL
```

but the old - for several reasons replaced - helper `isUntypedProperty` worked for this case

https://github.com/neos/neos-development-collection/blob/25772499d1b77fe0beb620393ea8466189df1067/Neos.Fusion/Classes/FusionObjects/DataStructureImplementation.php#L94

we need this new behaviour `isUntyped` to fix #3513 and #3441 - but now we have this issue ...
i could imagine creating here a flat ast for the `null` case (https://github.com/neos/neos-development-collection/blob/24d407118a8e55f7a96f1b69b244f9eeb8c561ac/Neos.Fusion/Classes/Core/Runtime.php#L659).

In general fusion has no good concept of null (the runtime cannot tell if a path was set to null or if it doesnt exist if you do `foo = null`)

**Comment by kitsunet** [comment] 2022-10-27 11:36
This is the reason I am against such conditional changes of behaviour (as we discussed for @if and process), I am not a fan of the DataStructure magic either. What if we would silently convert value `null` to ellExpression `${null}`, bit of a hack really. or ignore value null in the isUntpyedProperty check.

**Comment by mhsdesign** [comment] 2022-10-27 11:47
dont forget the case -> match magic ^^

yes this would be working for https://github.com/neos/neos-development-collection/blob/24d407118a8e55f7a96f1b69b244f9eeb8c561ac/Neos.Fusion/Classes/Core/Runtime.php#L659
```
if ($entry['value'] === null) {
    $valueAst = [
        '__eelExpression' => 'null',
        '__objectType' => null,
        '__value' => null
    ];
} else {
    $valueAst = [
        '__eelExpression' => null,
        '__objectType' => null,
        '__value' => $entry['value']
    ];
}
```

but reeeeeaaaalllyyyy messy and hacky ... 


maybe fix this
> In general fusion has no good concept of null (the runtime cannot tell if a path was set to null or if it doesnt exist if you do foo = null)

**Comment by mhsdesign** [comment] 2023-09-07 11:22
This problem also appears when unsetting paths:

```
renderer = Neos.Fusion:DataStructure {
    someProperty >
}
```


renders in 8.0 / 9.0

```
{"someProperty":[]}
```

before 8.0

we got an empty array
```
[]
```

**Comment by bwaidelich** [comment] 2024-04-30 12:15
> This problem also appears when unsetting paths

I'm afraid this is a major regression.

We stumbled upon this because some Monocle useCases didn't work as expected but this changes the behavior for very common constructs like

```fusion
# remove structured data from this site
prototype(Neos.Seo:StructuredData.Container) {
    breadcrumb >
    socialProfile >
    website >
}
```

@mhsdesign you mentioned a hacky fix. Can we try to get this into some PR so that we can at least pull that in via composer patches? I'm happy to help but I did not yet fully grasp the regression

**Comment by mhsdesign** [comment] 2024-04-30 13:38
Hmm i think the hack i proposed would only fix the apply issue and yield in your case `{breadcrumb:null}` values instead of unsets. (With unset i think we just want to completely unset that array key).

I have to think on this a little longer to create even a hacky patch 😅 

Also there is this related regression https://github.com/neos/neos-development-collection/issues/4499


As a really ugly hotfix, one could replace the data structure implementation in the cases for monocle and then reimplement the old `isUntyped` logic from 7.3 https://github.com/neos/neos-development-collection/blob/25772499d1b77fe0beb620393ea8466189df1067/Neos.Fusion/Classes/FusionObjects/DataStructureImplementation.php#L94 instead of https://github.com/neos/neos-development-collection/blob/a761d145a16d31eaf06bd52392cd93ceb6f109d1/Neos.Fusion/Classes/FusionObjects/AbstractArrayFusionObject.php#L214

**Comment by mhsdesign** [comment] 2024-06-16 15:48
fixed via https://github.com/neos/neos-development-collection/pull/5033 i guess

**Closed by mhsdesign** 2024-06-16 15:48 UTC
Labels: Bug
