### ISSUE TITLE
Live-Search in Data-Source

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-development-collection#1285] opened 2016-12-01 08:20 UTC
### Description
As an integrator i'd like to use a data source to select a property for my node. Right now you can do this and implement the `getData()` method within your class that extends `AbstractDataSource`. 
`getData()` will return all possible values. This is good as far as your data set is small. 

#### Expected behavior

A data source should also be able to search for a user input and return data that belong to that search term.

**Comment by kitsunet** [comment] 2017-04-30 23:42
Closing as duplicate of https://github.com/neos/neos-development-collection/issues/1421

**Closed by kitsunet** 2017-04-30 23:42 UTC
