### ISSUE TITLE
BUG: Cut & paste does not work if new parent does not exist in original dimension

### ISSUE THREAD

**Issue by pKallert** [neos/neos-development-collection#5368] opened 2024-11-15 08:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When cut & pasting a node using the "gatherAll" strategy in a dimension where the new parent does not exist in the original dimension, I get an error: https://github.com/neos/neos-development-collection/blob/9.0/Neos.ContentRepository.Core/Classes/Feature/NodeMove/NodeMove.php#L129 

<img width="568" alt="image" src="https://github.com/user-attachments/assets/394b635b-6d66-4e0b-95f4-f305ff8cf44a">

> Node aggregate "75b063ce-c1cb-420e-a806-be34bbdd61cf" does not cover expected dimension space point set [{"language":"en_US"},{"language":"de"},{"language":"en_UK"}] but [{"language":"de"}].

<details>

<summary>unrelated</summary>

Right now locally I am running into the error 
![Bildschirmfoto 2024-11-15 um 09 45 59](https://github.com/user-attachments/assets/497c31a0-4128-4563-ab8f-7f5ee8a506e2)

</details>

~Hint: I hard-coded the Strategy to SCATTER in the Neos UI~

### Expected Behavior

I would expect the same behavior as in 8.3 -> that I can cut& paste content to a parent even if the parent does not exist in the "original" dimension 

### Steps To Reproduce

1. Copy & create "Features > Multiple Columns" to german
2. Create new page in German under home named "Testing" 
3. Create "Three column element" in Testing 
4. Publish All
5. Cut & Paste Any Content inside the columns in "Multiple Columns" to "Three column element" in "Testing"
6. Error is thrown

### Environment

```markdown
- Flow:
- Neos:
- PHP:
```

**Comment by mhsdesign** [comment] 2024-11-22 11:07
We should try to relax the constraint checks and introduce a test for this

**Comment by kitsunet** [comment] 2024-11-30 11:46
Just realized it's a mysql syntax error for you locally there, probably because your DB version doesn't support COLUMNS access to JSON yet, this is supported from:

MariaDB starting with [10.6.0](https://mariadb.com/kb/en/mariadb-1060-release-notes/)[¶](https://mariadb.com/kb/en/json_table/#)

So maybe that fixes it already?

**Comment by mhsdesign** [comment] 2024-12-01 10:07
Paulas db is too old shes using `MariaDB 10.5` see https://github.com/neos/neos-development-collection/issues/4337

but the actual problem is still there, will update the description with the error once i reproduce it.

edit tested and updated

and after that error the paste button seems to be broken :D

<img width="668" alt="image" src="https://github.com/user-attachments/assets/d230b032-264e-42d5-821c-fe9834256a8c">


-> this is actually a bug in 8.3: https://github.com/neos/neos-ui/pull/3890/

**Comment by mhsdesign** [comment] 2024-12-01 10:33
EDIT: i forgot to pull the ui update

but with https://github.com/neos/neos-ui/pull/3876 i can confirm that it really works!

i suspect that

> Hint: I hard-coded the Strategy to SCATTER in the Neos UI

was not done when you (paula) tested that originally and now the db error came into play.

So indeed can be closed.

I also checked 22 from 137 behat test failed if i mess with the logic and cases like

> Scenario: Scatter a node aggregate by moving a specialization variant to a different parent. Then let a sibling variant follow suit and move the sibling before the node in both variants.

> Move a single node after the last of its siblings, which does not exist in all variants

seem to say its perfectly tested and working!

**Comment by mhsdesign** [comment] 2024-12-01 10:36
Though the problem - as desired? - persists for document nodes which are still gather all:

<img width="654" alt="image" src="https://github.com/user-attachments/assets/f5337fe6-7857-4370-816f-2f38e3baa96f">

I cannot move the variant 'multiple columns' beneath 'german only' and for that case we might have to offer 'scatter' _or_ at least display a nice message as this is not a bug but bad intention. And the optimistic node move by the neos ui is now in the wrong state (fixed after reload)

**Comment by kitsunet** [comment] 2024-12-01 11:30
> Though the problem - as desired? - persists for document nodes which are still gather all:

> I cannot move the variant 'multiple columns' beneath 'german only' and for that case we might have to offer 'scatter' _or_ at least display a nice message as this is not a bug but bad intention.

right but at least this is to be expected if it's not scatter.

**Comment by mhsdesign** [comment] 2024-12-01 13:18
Nice :D First win! 

the page move as described here: https://github.com/neos/neos-development-collection/issues/5368#issuecomment-2509679384 is also broken for Neos 8.3

> Node Multiple columns can not be moved. When moving Document Nodes, they are moved across all dimensions. For node Multiple columns, we attempted to move it across the following dimensions: - Language English (US) (ERROR: Non-Existing Parent) - Language English (UK) (ERROR: Non-Existing Parent) - Language French

<img width="835" alt="image" src="https://github.com/user-attachments/assets/37162ae6-32ed-474c-ae8c-bce377caa8ff">

So for the release its okay to keep that behaviour.
In the future i could imagine either detecting that case from the Neos ui and then offering scatter or introducing a `gatherAllIfPossible` strategy to prevent failure.

Though it might still make sense to make the error message a little nice for now ;)

**Comment by dlubitz** [comment] 2024-12-02 15:22
Tests have been added here: https://github.com/neos/neos-development-collection/pull/5384/files#diff-d86d8dcc7cb78398ebf7af3266b121067680af0ba66dde88dbefc3b6ce5d1012

**Comment by mhsdesign** [comment] 2024-12-05 12:38
so closing this as it has been fixed via https://github.com/neos/neos-ui/pull/3876

**Closed as completed by mhsdesign** 2024-12-05 12:38 UTC
Labels: Bug, 9.0
