### ISSUE TITLE
Hidden content is visible in the preview of your own workspace

### ISSUE THREAD

**Issue by mathiastonn** [neos/neos-development-collection#1585] opened 2017-05-24 05:56 UTC
### Description
We work with Workspaces and give our Clients the Url with Workspace-prefix to show the Preview of the pages. If we have hidden content it is displayed nevertheless . (No backenduser is login)

### Steps to Reproduce

1. Backend logon 
2. Create workspace
3. Switch to workspace
4. Create page
5. Create elements on page
6. Hide some elements on page.
7. Publish to workspace (not Live)
8. Click button "Open page in target workspace""
9. Backend logoff
10. reload browser-tab with page in target workspace

#### Expected behavior

show only content that is visible

#### Actual behavior

show all content

### Affected Versions

testet with Neos 3.0.1 and upper
 

Neos: 

Flow: 

You can get this information by running `composer show` or using the package management module within Neos.

**Comment by robertlemke** [comment] 2017-06-02 10:38
I can confirm this behaviour both on Neos 2.3.x and 3.1.x.

**Comment by bwaidelich** [comment] 2019-08-23 11:14
This has been fixed in the meantime, since shared workspace links are no longer supported (out of the box)

**Closed by bwaidelich** 2019-08-23 11:14 UTC
Labels: Bug, P: Content Repository, P: Neos, T: PHP
