### ISSUE TITLE
Composer deletes Readme.rst ?

### ISSUE THREAD

**Issue by dimitriadisg** [neos/neos-development-collection#1856] opened 2018-01-19 14:46 UTC
### Description

Hello,

recently I noticed that my changes in the root Readme.rst were gone and today I found out why.

For some reason, every time I run `composer install` or `update`, `require`, etc my root Readme.rst gets reset to the  "Welcome to Flow ..." introduction that comes wth Neos by default.

### Steps to Reproduce

1. Do some changes to Readme.rst
2. Run `composer require monolog/monolog`
3. Check if your changes in Readme.rst are there

#### Expected behavior

Normally, you should be able to see your changes in Readme.rst

#### Actual behavior

Any changes to Readme.rst are gone. The whole Readme.rst file is replaced by the one you get upon a clean installation.

### Affected Versions

Neos: 3.2.1

Flow: 4.2.5

**Comment by rolandschuetz** [comment] 2018-04-12 18:15
Not clearly a bug, but I see your point. An easy solution is to just use `README.md`

This could be fixed by moving the flow-development-collection/Neos.Flow/Resources/Private/Installer/Distribution/Essentials/Readme.rst into the Defaults folder.

**Comment by jonnitto** [comment] 2018-05-03 09:44
As @rolandschuetz said, this is not clearly a bug, it is by design like that. Is it ok for you if we close this issue?

**Comment by dimitriadisg** [comment] 2018-05-05 12:34
Alright, I guess I'll use a different file for documentation (readme.md sounds good), thanks !

Sure, feel free to close this, if it's intended functionality.

**Comment by kitsunet** [comment] 2018-05-05 12:38
I think it's not unteresting to think about better ways to do this. I am also not super happy about it. Maybe we can drop them somewhere else or just link to them and not put them in the root at all...

**Comment by jonnitto** [comment] 2018-05-07 10:05
I'm also not super happy with these files (because I never use them), but I don't have any good idea how to solve this differently

**Comment by maxstoyanov** [comment] 2018-09-19 12:57
I would just discard the readme and upgrading file. I don't know how many actually need the files but the information is available elsewhere...

**Closed** 2018-11-05 09:50 UTC
Labels: I: Needs feedback
