### ISSUE TITLE
BUG: Can't switch from internal workspace back to live

### ISSUE THREAD

**Issue by dlubitz** [neos/neos-development-collection#5129] opened 2024-06-05 12:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In latest 9.0 to switch from a "internal workspace" back to "live" the process seems to run into an infinite loop. CPU goes up to 100% and no response anymore. 

### Expected Behavior

I can switch back to live workspace as baseworkspace of my user workspace.

### Steps To Reproduce

Create new internal Workspace "Test"
Switch to "Test"
Switch to "Live"

### Environment

```markdown
- Flow: 9.0
- Neos: 9.0
- PHP: 8.2
```

**Comment by crydotsnake** [comment] 2024-06-14 13:34
Could reproduce it too.

**Comment by crydotsnake** [comment] 2024-06-14 13:37
If you then kill the `./flow server:run` process and start it again, it wont work:

```
Server running. Please go to http://127.0.0.1:8081 to browse the application.
[Fri Jun 14 15:35:23 2024] Failed to listen on 127.0.0.1:8081 (reason: Address already in use)
```

**Comment by ahaeslich** [comment] 2024-07-23 14:49
This might be a duplicate of https://github.com/neos/neos-ui/issues/3787

**Closed as completed** 2024-07-26 18:55 UTC
Labels: Bug, 9.0
