### ISSUE TITLE
German umlauts are broken in asset list

### ISSUE THREAD

**Issue by markusguenther** [neos/neos-development-collection#1775] opened 2017-11-30 11:48 UTC
### Description

When you create a new asset lists and assign assets with umlauts like ü in the file name, then the listing in the asset editor is fine but in the page the umlauts are broken.

![bildschirmfoto 2017-11-30 um 12 36 45](https://user-images.githubusercontent.com/1014126/33429316-984ff906-d5cc-11e7-836c-cad6adf1d1f9.png)

I already reported the issue in the Neos.Neos.Ui Repository but it also happens in the old UI.
https://github.com/neos/neos-ui/issues/1367

### Steps to Reproduce

1. Create new asset list
2. add asset with ö,ü or ä in the filename
3. apply the changes

#### Expected behavior

That the file name is correct like in the AssetEditor

#### Actual behavior

In the Website view the asset filename breaks the German umlaut.

### Affected Versions

Neos: used neos master

**Comment by jonnitto** [comment] 2017-12-06 15:21
Hi @markusguenther 
I can't reproduce this error. Is this fault also on the frontend? I had this error once, but it was the used font.

<img width="614" alt="screenshot 2017-12-06 16 21 28" src="https://user-images.githubusercontent.com/4510166/33669006-8b83449c-daa1-11e7-85ce-6167ef554c66.png">

**Comment by markusguenther** [comment] 2017-12-07 19:30
Ok it seems that it is an Firefox issue. But it is broken in the FE and BE.

**_Frontend Safari_**
<img width="962" alt="bildschirmfoto 2017-12-07 um 20 15 46" src="https://user-images.githubusercontent.com/1014126/33733909-8ab5680c-db8b-11e7-8a0c-2c0bd7c3e257.png">

**Frontend Firefox**
<img width="822" alt="bildschirmfoto 2017-12-07 um 20 15 24" src="https://user-images.githubusercontent.com/1014126/33733910-8afa55ac-db8b-11e7-8888-fa776a16787c.png">

**Backend Firefox**
<img width="1827" alt="bildschirmfoto 2017-12-07 um 20 13 57" src="https://user-images.githubusercontent.com/1014126/33733911-8b1e1488-db8b-11e7-8651-3a146f5e372c.png">

**Backend Safari**
<img width="1581" alt="bildschirmfoto 2017-12-07 um 20 13 06" src="https://user-images.githubusercontent.com/1014126/33733912-8b434f64-db8b-11e7-9cbb-e0dabc6cc7fe.png">

Have latest version of both.

Safari 11 and Firefox 57

**Comment by rolandschuetz** [comment] 2018-04-11 14:08
Hello,

I know the bug and also know how to reproduce it. The problem here is that this is not a real German Umlaut. Instead, these are two separate characters (used e.g. in compressed PDFs) when the font might now support full Unicode.

Sadly there is no easy fix for this in the core. It would require the PHP Unicode support package as additional Neos dependency. 

Here's how we fixed it for our projects:
https://github.com/rolandschuetz/neos-unicodenormalizer

**Closed** 2022-07-19 20:48 UTC
Labels: Still valid? Needs reproduction
