### ISSUE TITLE
Asset-usage shows "Broken Node" for usages with unpublished parent-node in foreign workspaces

### ISSUE THREAD

**Issue by mficzel** [neos/neos-development-collection#1599] opened 2017-05-31 14:41 UTC
### Description

Asset-usage shows "Broken Node" for usages with unpublished parent-node in foreign workspaces

### Steps to Reproduce

1. As a user i create a new node (grid or document) and inside of that i create a new image-contentNode and select an asset (both nodes stay unpublished).
2. As another user i open the media module select the asset and look at the usages. 
3. I see a “Broken node” reference for the two nodes that use the image but have unpublished parent nodes.

#### Expected behavior

The title of the closest document should be rendered and in addition an icon with a link to the document in live-workspace.

#### Actual behavior

Currently rendering the title and link+icon for an asset in a foreign workspace only works if the parent is already published. For nodes that have unpublished parents an Icon with an exclamation-mark is rendered with the rollover text "Broken Node".

### Affected Versions

At least Neos 3.0 and 3.1 maybe older ones are affected aswell.

**Comment by aertmann** [comment] 2017-06-01 15:08
might be fixed with #1578

**Comment by robertlemke** [comment] 2018-02-21 10:44
For the record, the "broken node" reference in the media browser looks like this for the second user:

![image](https://user-images.githubusercontent.com/95582/36475887-79b4ffac-16fc-11e8-8eae-b8b69f17ba0e.png)

**Comment by robertlemke** [comment] 2018-02-21 11:12
I can confirm that this would be fixed by #1578 (tested on Neos 2.3.x-dev).

Just one question though: by that fix a use will be able to see the name of documents he does not really have access to. Which is just a continuation of the problem that a user can see assets uploaded by a different user which were not published yet.

Given that the CEO of a company prepares an article "Acme Inc. sold to Saruman" and attaches a PDF file with further details, an unprivileged user would be able to a) find that PDF (that always has been possible) and b) see to which unpublished article it relates to (that would be new behavior).

The question is: should we allow this further disclosure now and tackle the overall problem separately or is any further leakage of information to be avoided?

**Comment by robertlemke** [comment] 2018-02-21 11:24
How about displaying the node identifier of the document node, so you at least have some kind of reference, in case you need to?

**Comment by kdambekalns** [comment] 2018-02-21 12:02
Yes, identifier would be great.

**Comment by robertlemke** [comment] 2018-02-21 14:08
Resolved by #1578

**Closed by robertlemke** 2018-02-21 14:08 UTC
Labels: P: Media Browser, T: PHP
