### ISSUE TITLE
Some Translation-files (.xlf) are not updated against "en"

### ISSUE THREAD

**Issue by ChKoeppel** [neos/neos-development-collection#3376] opened 2021-07-06 14:49 UTC
### Description

Some actions in the Backend (like user creation or editing) 
- lead to Errors of kind  '**The message body must be of type string, "NULL" given.**'
As some relevant xlf-Files **"Main.xlf"** and **"Modules.xlf"** are apparently **not updated** against **"en"** in **any language** (as I see)
- the **translation-ID**s of the corresponding "flash-message-body" **are missing** in those languages
- and this throws consequently the mentioned error

### Steps to Reproduce

1. The administrator's "**interfaceLanguage**" has to be set to "**german**" ...
2. Trying now the user-interface: ... editing some user details 
3. this **throws** now the mentioned **error** (caused by the missing translation-Id of the flash-message-body)
4. changing again the administrator's **user-language** to "**english**" - as this is not possible in the ui (error thrown), - you can do this in the database directly ... 
5. this **solves** the issue and the flash-message works correctly again ...

#### Expected behavior

The flash-message should work in any language

#### Actual behavior

Thrown error due to missing translation-id :  '**The message body must be of type string, "NULL" given.**'

### Affected Versions

Neos: 7.1

**Notice**:
Am I wrong to think that generally **every** translation-ID has normally to be present in any other language ??
(= **updated** xlf-files against "**en**")
I've seen the issue #3345 ... so if this description here is irrelevant now, - please close it ... thanks.

**Comment by albe** [comment] 2021-07-06 18:22
Thanks for the detailed report and sorry that the time you took was in vain :|
Closing as duplicate of https://github.com/neos/neos-development-collection/issues/3345

**Closed by albe** 2021-07-06 18:22 UTC
