### ISSUE TITLE
Neos 5.2 Node Tree doesn't update labels

### ISSUE THREAD

**Issue by abteilung** [neos/neos-development-collection#2979] opened 2020-05-10 10:28 UTC
### Description

In Neos 5.2, the Document Tree and the Content Tree don't update labels unless you refresh the Node Tree or reload the page entirely.

### Steps to Reproduce
![Eingefügtes_Bild_10_05_20__12_25](https://user-images.githubusercontent.com/906305/81496724-00032580-92ba-11ea-8cdd-e3ea99d558f6.png)

1. Install Neos 5.2
2. Update Node Name (e.g. Page title or Node title)
3. Hit "Apply"
4. Node labels in the Node Tree don't update
5. Hit "Refresh" in the tree
6. See updated labels

#### Expected behavior

1. Install Neos 5.2
2. Update Node Name
3. Hit Apply
4. See updated label in the Node Tree

### Affected Versions

Neos: 5.2

Neos-ui: 5.1.x, 5.2.x

Flow: 6.2

PHP: 7.2.x, 7.3.x, 7.4.x

**Comment by Sebobo** [comment] 2020-06-25 05:23
Thx for creating the issue. I'll close it as it's a duplicate of https://github.com/neos/neos-ui/issues/2665

**Closed** 2020-06-25 05:24 UTC
