### ISSUE TITLE
BUG: FA icon `house` is missing

### ISSUE THREAD

**Issue by simonschaufi** [neos/neos-development-collection#4413] opened 2023-07-26 04:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I wanted to use the `house` icon but it is not available even though it should be available since FA 1.0.0, see https://fontawesome.com/icons/house?f=classic&s=solid

I don't really understand what is going on in Neos as there is a file `Packages/Application/Neos.Neos/Resources/Private/Styles/FontAwesome/_variables.scss` and another one `Packages/Application/Neos.Neos/Resources/Private/Styles/_FontAwesomeVariables.scss` where icons are referenced but nowhere is the house icon. Then there is addidionally the fiile `Packages/Application/Neos.Neos/Resources/Public/Library/fontawesome/scss/_icons.scss` which confuses me even more. Last but not least there is some mapping going on here: `Packages/Application/Neos.Neos.Ui/packages/react-ui-components/src/Icon/mapper.ts`

I would love to create a PR to fix it but I don't know where to start.

### Expected Behavior

Icon is available

### Steps To Reproduce

Create a node type and use the `house` icon.

### Environment

```markdown
- Flow: -
- Neos: v7.3.19 but i believe all of the older releases are affected
```

**Comment by dlubitz** [comment] 2023-07-26 07:08
Thanks for you contribution. AFAIK the mapping of icons is not needed anymore. You could simple use the FA icons of the in Neos backend used current used FA version. 

E.g.: 
```
'Vendor:Page':
  superTypes:
    'Neos.Neos:Document': true
  ui:
    label: Page
    icon: 'fas fa-file'
```

Regarding the house-icon, this is a Pro-Icon, which is not included in the used Free-Version of FA:
https://fontawesome.com/v5/icons/house?f=classic&s=solid

If you must use this, you need to find a way to include the Pro-Version of FA in the Neos Backend.

I'd close this issue for now, as this is not a bug of Neos.

**Closed as not planned by dlubitz** 2023-07-26 07:08 UTC
Labels: Bug

**Comment by simonschaufi** [comment] 2023-07-26 23:23
Ok. I understand.
Please close the issue next time with the other mode as you haven’t fixed anything. Thank you
