### ISSUE TITLE
Remove Ember UI

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-development-collection#2531] opened 2019-05-28 08:12 UTC
Minimum requirement: The EmberJS must not be available in Neos 5.0.

- [x] Remove the old content module and other script from be-modules 
- [x] Rewrite the bar / menu in CSS vanilla JS -> @markusguenther 
- [x] Implement SessionStorage
- [x] Implement ConfigurationService
- [x] Implement NotificationService
- [x] Implement LocalisationService
- [x] Remove the Ember JS 
- [x] Remove corresponding build chain parts
- [x] Remove includes
- [x] Remove still existing fallback configurations
- [x] Check and remove Fusion parts that are overwritten in Neos.UI
- [ ] Check and remove PHP parts that are overwritten in Neos.UI
- [x] Check which ViewHelpers from Neos.Neos/Classes/ViewHelpers/Backend are still needed and remove the others
- [x] Check which ViewHelpers from Neos.Neos/Classes/ViewHelpers/Backend are still needed and remove the others
- [ ] Check which Endpoints from Neos.Neos/Classes/Controller/Backend are still needed and remove the others
- [ ] Remove obsolete styles from  Neos.Neos/Classes/Resources/Private/Styles/Neos.scss
- [x] Remove obsolete js libraries from Neos.Neos/Classes/Resources/Public/Library
- [x] Update Toolchain to latests version (webpack 5) #3305

**Comment by markusguenther** [comment] 2019-08-19 20:20
Ah did not look into that issue... Already tackling parts of that in the PR.
https://github.com/neos/neos-development-collection/pull/2536

Created my own little checklist :/

The TopBar and Menu is already working.
Now I am on the tree component and then on the flashmessages and I18n stuff :)

**Comment by markusguenther** [comment] 2019-09-04 19:51
As we now have a hybrid solution caused by the limited time this checklist is more or less outdated.
The ContentModule of the EmberUi has been removed and I removed as much Code as I could.

Ok sometimes bit too much but that will be back when the BUGFIX PRs has been merged.
For the new Release 5.1 I will try to get rid of the rest.

Maybe we can also get rid of the sass stuff and use the same software stack as the react-ui.
Because there we have postcss instead of sass and if we streamline the software stack (one part has been done as we are now also using webpack instead of grunt), we could also reuse packages like the build_essentials of the neos-ui for instance.

Maybe we can talk about that topic in vienna :)

**Comment by markusguenther** [comment] 2019-11-30 12:40
In this release I just made it to replace the stuff in the configuration module.
So the ticket will survive for the next release 5.2 :/

**Comment by albe** [comment] 2020-04-03 12:38
What is the latest status on this one? :)

**Comment by albe** [comment] 2020-04-28 10:55
Please keep going with this ;) Feels like there's probably only the last famous 20% missing (?)

**Comment by bwaidelich** [comment] 2020-09-11 07:01
> Please keep going with this ;) Feels like there's probably only the last famous 20% missing (?)

Yes please! <3

**Comment by markusguenther** [comment] 2020-09-11 08:01
In general I planned to do that for the release. I had a few private circumstances that prevented me from doing so.
My goal for the 6.0 is to replace the flashmesage handling and the translation with vanillajs stuff.

So that we get rid of that.

**Comment by markusguenther** [comment] 2020-11-27 09:14
Need to update that issue for the next minor release ... need also to refactor the todo list.

**Comment by markusguenther** [comment] 2021-03-10 20:48
Checked the todos and to be honest will try to make it until the release but can not promise that 🙈

**Closed** 2021-07-29 09:37 UTC
Labels: next minor
