### ISSUE TITLE
Data lose if emoji is used in property with MySQL database (Neos 3.3)

### ISSUE THREAD

**Issue by akappler** [neos/neos-development-collection#2091] opened 2018-06-21 13:33 UTC
### Description

If an editor adds an emoji e.g. 🔐 to a property e.g. of a document and the system uses a MySQL database, MySQL will not complain about an invalid string and saves an empty `{}` in the `property` column of the node. Therefore all data in `property` are lost, which will also break the page as the `uriPathSegement` is missing. 
Therefore neither the document tree in the backend nor the frontend is working anymore till this nodes get fixed.

### Steps to Reproduce
Important, it has to be *MySQL* database! 
MariaDB throws an error, which is shown to the editor and doesn't save it.

1. Select any document in the document tree and note the identifier of this document
2. Check in table `neos_contentrepository_domain_model_nodedata` the property of the document
3. Add 🔐 to the title, meta description or any property of a document node
4. Publish to live
5. Document tree won't work now only on nodes below the changed document
6. Search in table `neos_contentrepository_domain_model_nodedata` for the noted identifier 
7. The column `property` has now as value `{}`

#### Expected behavior

As emojis are not supported an error should be shown in all cases

#### Actual behavior

The invalid string get's saved to the `property` and MySQL is overwriting `property` with an empty `{}` 

### Affected Versions

MySQL: only tested with 5.5.59 (UTF-8 Unicode, coallation uft8_unicode_ci)

Neos: only tested with 3.3.11
Neos ReactUI: all versions affected
Flow: only tested with 4.3.6

**Comment by kitsunet** [comment] 2018-06-21 13:53
Closing as duplicate of already closed https://github.com/neos/neos-development-collection/issues/869

This is a won't fix because a fixed version exists and fixing it in old versions would be non trivial.

**Comment by kitsunet** [comment] 2018-06-21 14:17
If someone has a really good idea...

**Comment by kdambekalns** [comment] 2018-10-29 22:04
No…

**Closed by kdambekalns** 2018-10-29 22:04 UTC
